kakao:
  api:
    key: "ebb140871ec864bf632eb220b2c8f333"



server:
  port: 8081  # 서버 포트 번호 설정 (예: 8081)

  servlet:
    context-path: /api  # 기본 URL 경로 설정 (예: /api)

spring:
  data:
    redis:
      host: localhost         # Redis 서버 호스트 (기본값: localhost)
      port: 6379             # Redis 서버 포트 (기본값: 6379)
      password:              # Redis 비밀번호 (필요한 경우)
      database: 0            # Redis 데이터베이스 번호 (기본값: 0)
      timeout: 2000          # 연결 타임아웃 (밀리초)
      ssl:
        enabled: false


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/playground?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: Wjdals12!
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  messages:
    basename: messages

  ## 업로드 파일 설정
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB
      file-size-threshold: 2KB

spring-doc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
    doc-expansion: none

file:
  upload:
    path: uploads\\ # 파일 업로드 기본 경로

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

