kakao:
  api:
    key: "ebb140871ec864bf632eb220b2c8f333"

server:
  port: 8081

spring:
  data:
    redis:
      host: redis-container # 운영 환경에서는 도커 컨테이너 사용
      port: 6379
      password:
      database: 0
      timeout: 2000
      ssl:
        enabled: false

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: LvLgBDoxDkpt12w_uWf4
            client-secret: jYPs9EzRZI
            scope: name
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: https://hityundong.com/api/login/oauth2/code/naver

          google:
            client-id: 4259829940-5fchek1qftvv1i3nhqbjh4lc54pnfek0.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile
            redirect-uri: https://hityundong.com/api/login/oauth2/code/google

          github:
            client-id: Ov23li5J8FK2zQimI1DB
            client-secret: 27acd3c6996914a58ced2b54e8bd783136f6aa6b
            authorization-grant-type: authorization_code
            redirect-uri: http://3.35.210.236:8081/api/login/oauth2/code/github
            scope: read:user, user:email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-container:3306/toy?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user
    password: Wjdals12!
    hikari:
      maximum-pool-size: 10
      data-source-properties:
        rewriteBatchedStatements: true
        useUnicode: true
        characterEncoding: utf8
        autoReconnect: true
        useSSL: false
        requireSSL: false
        serverTimezone: Asia/Seoul
        sessionVariables: character_set_results=utf8mb4

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
