kakao:
  api:
    key: ${KAKAO_API_KEY:default-kakao-key} # 환경 변수에서 가져오기

server:
  port: ${SERVER_PORT:8081}

spring:
  data:
    redis:
      host: ${REDIS_HOST:redis-container} # 환경 변수 적용
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:} # 비밀번호가 없을 경우 기본값 비워둠
      database: 0
      timeout: 2000
      ssl:
        enabled: false

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${NAVER_CLIENT_ID:default-naver-client-id}
            client-secret: ${NAVER_CLIENT_SECRET:default-naver-client-secret}
            scope: name
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: https://hityundong.com/api/login/oauth2/code/naver

          google:
            client-id: ${GOOGLE_CLIENT_ID:default-google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:default-google-client-secret}
            scope: email, profile
            redirect-uri: https://hityundong.com/api/login/oauth2/code/google

          github:
            client-id: ${GITHUB_CLIENT_ID:default-github-client-id}
            client-secret: ${GITHUB_CLIENT_SECRET:default-github-client-secret}
            authorization-grant-type: authorization_code
            redirect-uri: http://3.35.210.236:8081/api/login/oauth2/code/github
            scope: read:user, user:email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME:default-db-user}
    password: ${DB_PASSWORD:default-db-password}
    hikari:
      maximum-pool-size: 10
      data-source-properties:
        rewriteBatchedStatements: true
        useUnicode: true
        characterEncoding: utf8
        autoReconnect: true
        useSSL: false
        requireSSL: false
        serverTimezone: Asia/Seoul
        sessionVariables: character_set_results=utf8mb4

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true


file:
  upload:
    path: ${FILE_UPLOAD_PATH:/uploads/}  # 기본값: /uploads/

jwt:
  secret: ${JWT_SECRET:default-secret-key}  # 기본값 설정