server:
  port: 8081
  servlet:
    context-path: /api

spring:
  profiles:
    active: dev # 기본 활성화 프로필 (dev)

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS_ENABLE:true}

  messages:
    basename: messages

  ## 업로드 파일 설정
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB
      file-size-threshold: 2KB


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html


