kakao:
  api:
    key: "ebb140871ec864bf632eb220b2c8f333"



server:
  port: 8081  # 서버 포트 번호 설정 (예: 8081)

  servlet:
    context-path: /api  # 기본 URL 경로 설정 (예: /api)

spring:
  data:
    redis:
      host: localhost         # Redis 서버 호스트 (기본값: localhost)
      port: 6379             # Redis 서버 포트 (기본값: 6379)
      password:              # Redis 비밀번호 (필요한 경우)
      database: 0            # Redis 데이터베이스 번호 (기본값: 0)
      timeout: 2000          # 연결 타임아웃 (밀리초)
      ssl:
        enabled: false


jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

