server:
  port: 8081
  servlet:
    context-path: /api

spring:
  profiles:
    active: dev # 기본 활성화 프로필 (dev)

  messages:
    basename: messages

  ## 업로드 파일 설정
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB
      file-size-threshold: 2KB


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html


