kakao:
  api:
    key: "ebb140871ec864bf632eb220b2c8f333"



server:
  port: 8081  # 서버 포트 번호 설정 (예: 8081)

  servlet:
    context-path: /api  # 기본 URL 경로 설정 (예: /api)

spring:
  data:
    redis:
      host: localhost         # Redis 서버 호스트 (기본값: localhost)
      port: 6379             # Redis 서버 포트 (기본값: 6379)
      password:              # Redis 비밀번호 (필요한 경우)
      database: 0            # Redis 데이터베이스 번호 (기본값: 0)
      timeout: 2000          # 연결 타임아웃 (밀리초)
      ssl:
        enabled: false

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: LvLgBDoxDkpt12w_uWf4
            client-secret: jYPs9EzRZI
            scope: name
            #- profile_image
            client-name: Naver
            authorization-grant-type: authorization_code
            #redirect-uri: http://localhost:8080/login/oauth2/code/naver
            redirect-uri: https://hityundong.com/api/login/oauth2/code/naver

          google:
            client-id: 4259829940-5fchek1qftvv1i3nhqbjh4lc54pnfek0.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile
            redirect-uri: https://hityundong.com/api/login/oauth2/code/google

          github:
            client-id: Ov23li5J8FK2zQimI1DB
            client-secret: 27acd3c6996914a58ced2b54e8bd783136f6aa6b
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/api/login/oauth2/code/github
            scope: read:user, user:email

        provider: #네이버의 provider는 등록되어 있지 않아 사용자가 등록해야된다.
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize #네이버 로그인 창을 받을수 있다
            token-uri: https://nid.naver.com/oauth2.0/token #토큰을 받는 uri
            user-info-uri: https://openapi.naver.com/v1/nid/me #프로필 주소를 받는 uri
            user-name-attribute: response #회원 벙보를 json 형태로 받는데 response 라는 키값으로 네이버가 리턴해줌

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/playground?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: Wjdals12!
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  messages:
    basename: messages

  ## 업로드 파일 설정
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB
      file-size-threshold: 2KB

spring-doc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
    doc-expansion: none

file:
  upload:
    path: uploads\\ # 파일 업로드 기본 경로

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

